# -*- coding: utf-8 -*-
"""ReversedDesertification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c51rzOZ_6V6Q_hutQF_96Zz_vJeF3cCI
"""

import ee
import pandas as pd
import numpy as np


PROJECT_ID = 'reversing-desertification'
ee.Initialize(project=PROJECT_ID)

# Defining Research ROIs (Bounding Boxes)
rajasthan_roi = ee.Geometry.BBox(73.8, 29.3, 74.3, 29.8)
gobi_roi = ee.Geometry.BBox(108.2, 40.2, 108.8, 40.8)

# Variable Map with Corrected Band Names and IDs
vars_map = {
    'NDVI':      {'id': "MODIS/061/MOD13Q1", 'band': 'NDVI', 'res': 500},
    'EVI':       {'id': "MODIS/061/MOD13Q1", 'band': 'EVI', 'res': 500},
    'LAI':       {'id': "MODIS/061/MCD15A3H", 'band': 'Lai', 'res': 500},
    'LST_Day':   {'id': "MODIS/061/MOD11A2", 'band': 'LST_Day_1km', 'res': 1000},
    'LST_Night': {'id': "MODIS/061/MOD11A2", 'band': 'LST_Night_1km', 'res': 1000},
    'Rain':      {'id': "UCSB-CHG/CHIRPS/DAILY", 'band': 'precipitation', 'res': 5000},
    'SoilMoist': {'id': "NASA/FLDAS/NOAH01/C/GL/M/V001", 'band': 'SoilMoi00_10cm_tavg', 'res': 10000},
    'Albedo':    {'id': "MODIS/061/MCD43A3", 'band': 'Albedo_WSA_shortwave', 'res': 500},
    'Evapo':     {'id': "MODIS/061/MOD16A2", 'band': 'ET', 'res': 500}
}

def fetch_data_failsafe(roi, start_date, end_date):
    date_list = ee.List.sequence(0, ee.Date(end_date).difference(ee.Date(start_date), 'month').subtract(1))
    start_ee = ee.Date(start_date)

    def process_month(n):
        m_start = start_ee.advance(n, 'month')
        m_end = m_start.advance(1, 'month')
        feature_dict = {'date': m_start.format('YYYY-MM-dd')}

        for name, info in vars_map.items():
            col = ee.ImageCollection(info['id']).filterDate(m_start, m_end).select(info['band'])

            # Using median for robustness against clouds
            img = col.median()

            # Performing reduction
            stats = img.reduceRegion(
                reducer=ee.Reducer.mean(),
                geometry=roi,
                scale=info['res'],
                maxPixels=1e9
            )

            # SAFE GET: Check if the key exists in the dictionary, otherwise return -9999
            val = ee.Dictionary(stats).get(info['band'], -9999)
            feature_dict[name] = val

        return ee.Feature(None, feature_dict)

    print("Requesting server-side computation (Failsafe Mode)...")
    raw_output = ee.FeatureCollection(date_list.map(process_month)).getInfo()
    features = raw_output['features']

    df = pd.DataFrame([f['properties'] for f in features])
    df['date'] = pd.to_datetime(df['date'])
    df = df.set_index('date').replace(-9999, np.nan)
    df = df.apply(pd.to_numeric, errors='coerce')

    # Scientific Scaling & Feature Engineering
    if 'NDVI' in df: df['NDVI'] *= 0.0001
    if 'EVI' in df: df['EVI'] *= 0.0001
    if 'LAI' in df: df['LAI'] *= 0.1
    if 'Albedo' in df: df['Albedo'] *= 0.001
    if 'LST_Day' in df:
        df['LST_Day'] *= 0.02
        df['LST_Night'] *= 0.02
        df['Temp_Delta'] = df['LST_Day'] - df['LST_Night']
    if 'Evapo' in df: df['Evapo'] *= 0.1

    # Handle gaps with interpolation
    df = df.interpolate(method='linear').ffill().bfill()
    return df


print("Starting high-accuracy extraction for Rajasthan and Gobi...")
df_rajasthan = fetch_data_failsafe(rajasthan_roi, '2005-01-01', '2023-12-31')
df_gobi = fetch_data_failsafe(gobi_roi, '2005-01-01', '2023-12-31')


import matplotlib.pyplot as plt
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 10))

df_rajasthan[['NDVI', 'LAI']].plot(ax=ax1, title="Vegetation Signature (Rajasthan)")
df_rajasthan[['Rain', 'SoilMoist', 'Evapo']].plot(ax=ax2, secondary_y=['Rain'], title="Hydrological Forcing")

plt.tight_layout()
plt.show()


df_rajasthan.to_csv('rajasthan_research_data.csv')
df_gobi.to_csv('gobi_research_data.csv')
print("\nSuccess! Files saved. Ready for non-linear analysis.")

import seaborn as sns

# Calculate correlation
corr = df_rajasthan.corr()

plt.figure(figsize=(10, 8))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Ecological Interaction Matrix: Rajasthan Canal")
plt.show()

# 1. Rate of Change of the ecosystem
df_rajasthan['dNDVI_dt'] = df_rajasthan['NDVI'].diff()

# 2. Smoothing the data to remove satellite noise
df_smooth = df_rajasthan.rolling(window=3).mean().dropna()

# 3. Phase Portrait
plt.figure(figsize=(8, 8))
plt.plot(df_smooth['NDVI'], df_smooth['dNDVI_dt'], alpha=0.6, color='forestgreen')
plt.axhline(0, color='black', lw=1)
plt.xlabel('Vegetation State (NDVI)')
plt.ylabel('Rate of Change (dNDVI/dt)')
plt.title('Ecological Phase Portrait: The Rajasthan Attractor')
plt.grid(True, alpha=0.3)
plt.show()

# Extracting only September data for every year (The Monsoon part)
poincare_slice = df_rajasthan[df_rajasthan.index.month == 9]

plt.figure(figsize=(10, 5))
plt.scatter(poincare_slice.index.year, poincare_slice['NDVI'], c=poincare_slice['SoilMoist'], cmap='YlGnBu', s=100)
plt.plot(poincare_slice.index.year, poincare_slice['NDVI'], alpha=0.3)
plt.colorbar(label='Soil Moisture')
plt.title("Poincaré Map: September Vegetation Peak (2005-2023)")
plt.ylabel("NDVI")
plt.xlabel("Year")
plt.show()

import numpy as np
from pysr import PySRRegressor

# 1. Preparing the Data
# Target (y): The difference in NDVI from one month to the next
y = df_rajasthan['NDVI'].diff().fillna(0).values

# Features (X): The state variables and drivers
features = ['NDVI', 'Rain', 'SoilMoist', 'LST_Day', 'Albedo', 'Evapo']
X = df_rajasthan[features].fillna(0).values

# 2. Configuring the Symbolic Regression Model
# We use basic operators to find a "Physics-like" equation
model = PySRRegressor(
    niterations=50,             # Number of search cycles
    binary_operators=["+", "*", "-", "/"],
    unary_operators=["exp", "sin", "cos"],
    constraints={'/': (-1, 9), 'exp': 9},
    model_selection="best",
    variable_names=features,
    loss="loss(prediction, target) = (prediction - target)^2" # Mean Squared Error
)


print("Searching for the Rajasthan Ecological Equation...")
model.fit(X, y)


print("\n--- Discovered Equations ---")
print(model)

import numpy as np
import matplotlib.pyplot as plt

def ecological_ode(NDVI, SoilMoist):
    # This is the math the ML found
    term1 = (0.6194 * SoilMoist) / (NDVI + 0.1389)
    dNDVI_dt = NDVI + term1 - 0.6079
    return dNDVI_dt

def rk4_step(v, s, dt):
    k1 = ecological_ode(v, s)
    k2 = ecological_ode(v + k1*dt/2, s)
    k3 = ecological_ode(v + k2*dt/2, s)
    k4 = ecological_ode(v + k3*dt, s)
    return v + (dt/6) * (k1 + 2*k2 + 2*k3 + k4)


years = 50
dt = 0.1 # Monthly steps
steps = int(years / dt)
time = np.linspace(0, years, steps)


v_current = 0.26
s_avg = df_rajasthan['SoilMoist'].mean()


trajectory = []
v = v_current
for i in range(steps):
    v = rk4_step(v, s_avg, dt)
    trajectory.append(v)

# Plotting the Forecast
plt.figure(figsize=(10, 5))
plt.plot(time, trajectory, color='darkgreen', lw=2)
plt.title("50-Year Forecast of Rajasthan Canal Ecosystem (RK4)")
plt.xlabel("Years from Today")
plt.ylabel("Projected NDVI")
plt.grid(True, alpha=0.3)
plt.show()

def calculate_lyapunov(v_start, s, iterations=1000, dt=0.01):
    v = v_start
    v_perturbed = v_start + 1e-6

    lyapunov_sum = 0

    for i in range(iterations):
        v_next = rk4_step(v, s, dt)
        v_p_next = rk4_step(v_perturbed, s, dt)

        # Calculating divergence
        distance = np.abs(v_next - v_p_next)
        lyapunov_sum += np.log(distance / 1e-6)

        # Rescale the perturbation
        v = v_next
        v_perturbed = v_next + (v_p_next - v_next) * (1e-6 / distance)

    return lyapunov_sum / (iterations * dt)

# Calculating for Rajasthan
lambda_val = calculate_lyapunov(v_current, s_avg)
print(f"\nDiscovered Lyapunov Exponent: {lambda_val:.4f}")

if lambda_val < 0:
    print("Conclusion: The ecosystem is STABLE (Fixed Point/Limit Cycle).")
else:
    print("Conclusion: The ecosystem is SENSITIVE/CHAOTIC (Tipping Point risk).")

# 1. Preparing Gobi Data
y_gobi = df_gobi['NDVI'].diff().fillna(0).values
X_gobi = df_gobi[features].fillna(0).values

# 2. Running PySR for Gobi
model_gobi = PySRRegressor(
    niterations=50,
    binary_operators=["+", "*", "-", "/"],
    unary_operators=["exp", "sin"],
    model_selection="best",
    variable_names=features
)

print("Searching for the Gobi Ecological Equation...")
model_gobi.fit(X_gobi, y_gobi)

print("\n--- Gobi Discovered Equations ---")
print(model_gobi)

import matplotlib.pyplot as plt


plt.style.use('seaborn-v0_8-whitegrid')
plt.figure(figsize=(12, 6))


plt.plot(time, trajectory,
         label=r"Rajasthan Canal (Irrigation) $\lambda$: -0.9240",
         color='darkgreen', lw=2.5)


plt.plot(time, traj_gobi,
         label=r"Gobi Green Wall (Afforestation) $\lambda$: -0.1646",
         color='orange', lw=2.5)

# Adding Threshold
plt.axhline(0.1, color='red', linestyle='--', alpha=0.6, label="Desert Threshold (Aridity)")

# Formatting
plt.title("Ecological Stability Forecast: Multi-Decadal Projection", fontsize=14)
plt.ylabel("NDVI (Vegetation Health Index)", fontsize=12)
plt.xlabel("Years into Future (Projected via RK4)", fontsize=12)
plt.ylim(-0.02, 0.3)
plt.legend(frameon=True, loc='upper right', fontsize=10)
plt.grid(True, alpha=0.3)

plt.savefig('Final_Sustainability_Forecast.png', dpi=300)
plt.show()

print("Analysis Complete.")
print(f"Rajasthan Stability: Strong Negative Attraction (Stable)")
print(f"Gobi Stability: Weak Negative Attraction (Fragile/Decaying)")